version: '3'
services:
    mongodb:
        image: mongo
        networks: 
            - production-network

    node1:
        build:
            dockerfile: ./Dockerfile
            context: .
        image: alaorjr/flask_docker
        container_name: flask_server
        ports:
            - "5000:5000"
        networks: 
            - production-network
        depends_on:
            - "mongodb"

networks: 
    production-network:
        driver: bridge